"""Pydantic models for the softball domain.

These primarily validate *writes* (the admin forms in Phase 3 build these and
call `.for_insert()`). Reads come back from the DB as plain dicts/DataFrames —
we don't force every query through a model, which keeps analytics fast and
flexible.

Conventions:
  * `*Create` models carry the fields a user supplies on insert/update.
  * Server-managed fields (id, created_at, generated `tb`) live only on the
    full read models.
  * `for_insert()` returns a JSON-ready dict (dates -> ISO strings) with None
    values dropped, so optional pitching columns aren't sent as nulls.
"""

from __future__ import annotations

from datetime import date, datetime

from pydantic import BaseModel, Field, model_validator


class _Payload(BaseModel):
    """Base for write payloads."""

    def for_insert(self) -> dict:
        # mode="json" serializes date/datetime to ISO strings for PostgREST.
        return self.model_dump(mode="json", exclude_none=True)


# --- Positions (reference) ------------------------------------------------

class Position(BaseModel):
    id: str
    code: str
    name: str
    category: str


# --- Teams ----------------------------------------------------------------

class TeamCreate(_Payload):
    name: str
    abbreviation: str | None = None
    season: str | None = None


class Team(TeamCreate):
    id: str
    created_at: datetime | None = None


# --- Players --------------------------------------------------------------

class PlayerCreate(_Payload):
    name: str
    team_id: str | None = None
    jersey_number: int | None = None
    primary_position_id: str | None = None
    positions: list[str] | None = None  # eligible position codes, e.g. ["SS", "2B"]
    bats: str | None = Field(default=None, pattern="^[LRS]$")
    throws: str | None = Field(default=None, pattern="^[LR]$")
    active: bool = True


class Player(PlayerCreate):
    id: str
    created_at: datetime | None = None


# --- Games ----------------------------------------------------------------

class GameCreate(_Payload):
    game_date: date
    season: str | None = None
    home_team_id: str | None = None
    away_team_id: str | None = None
    home_score: int = Field(default=0, ge=0)
    away_score: int = Field(default=0, ge=0)
    location: str | None = None
    status: str = Field(default="final", pattern="^(scheduled|in_progress|final)$")
    notes: str | None = None


class Game(GameCreate):
    id: str
    created_at: datetime | None = None


# --- Innings (line score) -------------------------------------------------

class InningCreate(_Payload):
    game_id: str
    inning_number: int = Field(ge=1)
    team_id: str | None = None
    half: str | None = Field(default=None, pattern="^(top|bottom)$")
    runs: int = Field(default=0, ge=0)
    hits: int = Field(default=0, ge=0)
    errors: int = Field(default=0, ge=0)


class Inning(InningCreate):
    id: str


# --- Player game stats (box-score line) -----------------------------------

class PlayerGameStatsCreate(_Payload):
    game_id: str
    player_id: str
    team_id: str | None = None
    position_id: str | None = None

    # Batting (all non-negative)
    ab: int = Field(default=0, ge=0)
    r: int = Field(default=0, ge=0)
    h: int = Field(default=0, ge=0)
    rbi: int = Field(default=0, ge=0)
    bb: int = Field(default=0, ge=0)
    so: int = Field(default=0, ge=0)
    doubles: int = Field(default=0, ge=0)
    triples: int = Field(default=0, ge=0)
    hr: int = Field(default=0, ge=0)
    lob: int = Field(default=0, ge=0)

    # Defense
    errors: int = Field(default=0, ge=0)

    # Pitching (optional; only for pitchers)
    ip: float | None = Field(default=None, ge=0)
    p_h: int | None = Field(default=None, ge=0)
    p_r: int | None = Field(default=None, ge=0)
    er: int | None = Field(default=None, ge=0)
    p_bb: int | None = Field(default=None, ge=0)
    p_so: int | None = Field(default=None, ge=0)
    p_hr: int | None = Field(default=None, ge=0)

    @model_validator(mode="after")
    def _logical_checks(self) -> "PlayerGameStatsCreate":
        # A hit requires an at-bat; you can't have more hits than at-bats.
        if self.h > self.ab:
            raise ValueError(f"hits ({self.h}) cannot exceed at-bats ({self.ab})")
        # Extra-base hits are a subset of total hits.
        xbh = self.doubles + self.triples + self.hr
        if xbh > self.h:
            raise ValueError(
                f"extra-base hits ({xbh}) cannot exceed hits ({self.h})"
            )
        return self


class PlayerGameStats(PlayerGameStatsCreate):
    id: str
    tb: int | None = None  # generated by the DB
    created_at: datetime | None = None


# --- Team game stats ------------------------------------------------------

class TeamGameStatsCreate(_Payload):
    game_id: str
    team_id: str
    runs: int = Field(default=0, ge=0)
    hits: int = Field(default=0, ge=0)
    errors: int = Field(default=0, ge=0)
    lob: int = Field(default=0, ge=0)
    ab: int = Field(default=0, ge=0)
    bb: int = Field(default=0, ge=0)
    so: int = Field(default=0, ge=0)


class TeamGameStats(TeamGameStatsCreate):
    id: str
    created_at: datetime | None = None
